const SHEETS = {project:'프로젝트대시보드', gates:'Gate관리', documents:'문서등록', experiments:'실험검증', risks:'리스크', roadmap:'로드맵', products:'제품파이프라인', policy:'공개정책', settings:'설정', technology:'기술요약', checklist:'자료체크리스트', claims:'Claim-Evidence', inquiries:'협업문의', routing:'문의라우팅', syncLog:'동기화로그', audit:'변경이력'};
const HEADERS = {project:['metric','value','source','lastUpdated'],gates:['id','area','title','description','passCriteria','status','weight','owner','targetDate','requiredEvidence','publicSummary','evidenceCount','checklistProgress','lastUpdated'],documents:['id','title','category','summary','status','publicationLevel','publicationApproved','sourceType','version','modifiedAt','owner','gateIds','claimIds','language','publicUrl'],experiments:['id','title','stage','sop','batchSize','resultSummary','verificationStatus','evidenceIds','lastUpdated'],risks:['id','title','severity','impact','mitigation','owner','status','lastUpdated'],roadmap:['id','year','title','items','status','owner'],products:['id','name','market','stage','status','description','targetDate'],policy:['publicationLevel','publicationApproved','allowedFields','prohibitedFields','reviewer','reviewedAt'],settings:['key','value','description'],technology:['id','name','type','role','status','publicSummary'],checklist:['id','area','item','status','evidenceIds','owner'],claims:['claimId','claim','claimType','evidenceLevel','evidenceIds','limitation','verificationStatus','reviewer','reviewedAt','publicWording','prohibitedWording'],inquiries:['requestId','submittedAt','status','categoryId','categoryName','name','company','role','email','phone','country','product','gateId','documentId','claimId','currentUrl','requestType','targetDate','expectedVolume','budgetRange','meetingPreference','ndaRequested','message','generatedSummary','consent','marketingConsent','source','assignee','responseDueAt','notifiedAt','closedAt'],routing:['categoryId','categoryName','active','recipientEmail','ccEmail','owner','requiredFields','optionalFields','defaultSubject','responseSlaHours','confirmationTemplate','retentionDays'],syncLog:['timestamp','action','status','message'],audit:['timestamp','action','message','actor']};
function prop_(key){return PropertiesService.getScriptProperties().getProperty(key)||'';}
const DRIVE_FOLDERS=['00_운영관리_웹인덱스','01_법인_지배구조_IP귀속','02_핵심기술_균주_특허','03_기술검증_재현성_분석','04_Scale-up_제조공정_원가','05_품질_QA_QC_규제','06_제품_시장_고객','07_ESG_바이오셀룰로오스_탄소','08_재무_KIFRS_내부통제','09_기술성평가_상장심사','10_투자_IR_데이터룸','99_원본_보관_비공개'];
function setupProject(){ensureSheetsAndHeaders();ensureDriveFolders_();installAutomation();scanDriveAndUpsertDocuments();buildPublicIndex();}
function ensureDriveFolders_(){const root=DriveApp.getFolderById(prop_('ROOT_FOLDER_ID')); DRIVE_FOLDERS.forEach(name=>{if(!root.getFoldersByName(name).hasNext()) root.createFolder(name);});}
function ensureSheetsAndHeaders(){const id=prop_('MASTER_SHEET_ID'); if(!id) throw new Error('MASTER_SHEET_ID is required'); const ss=SpreadsheetApp.openById(id); Object.values(SHEETS).forEach(name=>{const sheet=ss.getSheetByName(name)||ss.insertSheet(name); const headers=HEADERS[name]; if(headers&&!sheet.getLastRow()) sheet.getRange(1,1,1,headers.length).setValues([headers]);});}
function scanDriveAndUpsertDocuments(){const root=DriveApp.getFolderById(prop_('ROOT_FOLDER_ID')); const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const sheet=ss.getSheetByName(SHEETS.documents); const values=sheet.getDataRange().getValues(); const ids={}; values.slice(1).forEach((r,i)=>{if(r[0]) ids[String(r[0])]=i+2;}); const seen={}; const walk=(folder,folderPath)=>{const files=folder.getFiles(); while(files.hasNext()){const f=files.next(); const id=f.getId(); seen[id]=true; const row=ids[id]||sheet.getLastRow()+1; const old=ids[id]?sheet.getRange(row,1,1,15).getValues()[0]:[]; const v=[id,f.getName(),old[2]||'미분류',old[3]||'자동등록 문서',old[4]||'active',old[5]||'RESTRICTED',old[6]||'N',f.getMimeType(),old[8]||'1',f.getLastUpdated(),old[10]||'',old[11]||'',old[12]||'',old[13]||'ko',old[14]||'']; sheet.getRange(row,1,1,v.length).setValues([v]);} const folders=folder.getFolders(); while(folders.hasNext()){const child=folders.next(); walk(child,folderPath+'/'+child.getName());}}; walk(root,root.getName()); for(let i=2;i<=sheet.getLastRow();i++){const id=String(sheet.getRange(i,1).getValue()||''); if(id&&!seen[id]&&sheet.getRange(i,5).getValue()==='active') sheet.getRange(i,5).setValue('MISSING');} writeSyncLog('scanDriveAndUpsertDocuments','success',''); writeAuditLog('drive-scan',Object.keys(seen).length+' files');}
function buildPublicIndex(){const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const docs=ss.getSheetByName(SHEETS.documents).getDataRange().getValues().slice(1).filter(r=>r[5]==='PUBLIC'&&r[6]==='Y').map(r=>({id:r[0],title:r[1],category:r[2],summary:r[3],status:r[4],publicationLevel:r[5],publicationApproved:r[6],sourceType:r[7],version:r[8],modifiedAt:r[9],owner:r[10],gateIds:String(r[11]||'').split(',').filter(Boolean),claimIds:String(r[12]||'').split(',').filter(Boolean),language:r[13]})); const gateSheet=ss.getSheetByName(SHEETS.gates); const gates=gateSheet.getDataRange().getValues().slice(1).filter(r=>r[0]).map(r=>({id:r[0],area:r[1],title:r[2],description:r[3],passCriteria:r[4],status:r[5]||'not_started',weight:Number(r[6]||0),owner:r[7]||'',targetDate:r[8]||'',requiredEvidence:String(r[9]||'').split(',').filter(Boolean),publicSummary:r[10]||'',evidenceCount:Number(r[11]||0),checklistProgress:Number(r[12]||0),lastUpdated:r[13]||''})); const output={schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),source:{type:'Google Drive + Master Control',lastSyncedAt:new Date().toISOString()},project:{targetListingYear:2030,decision:'Conditional GO'},readiness:{note:'내부 관리지표'},gates:gates,technology:{},claims:[],documents:docs,experiments:[],risks:[],roadmap:[],products:[],esg:[],consultationCategories:[],publicationPolicy:{rule:'PUBLIC + Y only'},syncHealth:{mode:'apps-script',endpointConfigured:true,status:'published'}}; validatePublicIndex(output); return output;}
function validatePublicIndex(index){if(!index||!Array.isArray(index.documents)||!Array.isArray(index.gates)||index.gates.length!==10) throw new Error('Invalid public index or missing ten gates'); if(index.gates.reduce((sum,g)=>sum+Number(g.weight||0),0)!==100) throw new Error('Gate weights must total 100'); index.documents.forEach(d=>{if(d.publicationLevel!=='PUBLIC'||d.publicationApproved!=='Y'||d.publicUrl&&d.publicationLevel!=='PUBLIC') throw new Error('Publication boundary violation');}); return true;}
function publishPublicJson(){const index=buildPublicIndex(); validatePublicIndex(index); return JSON.stringify(index);}
function installAutomation(){const mins=Number(prop_('TRIGGER_MINUTES')||30); ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='scanDriveAndUpsertDocuments').forEach(t=>ScriptApp.deleteTrigger(t)); ScriptApp.newTrigger('scanDriveAndUpsertDocuments').timeBased().everyMinutes(Math.max(1,Math.min(60,mins))).create();}
function removeAutomation(){ScriptApp.getProjectTriggers().forEach(t=>ScriptApp.deleteTrigger(t));}
function sendGithubDispatch(){const pat=prop_('GITHUB_FINE_GRAINED_PAT'); if(!pat)return {ok:false,reason:'PAT not configured'}; const url='https://api.github.com/repos/'+prop_('GITHUB_OWNER')+'/'+prop_('GITHUB_REPO')+'/dispatches'; return UrlFetchApp.fetch(url,{method:'post',headers:{Authorization:'Bearer '+pat,Accept:'application/vnd.github+json'},contentType:'application/json',payload:JSON.stringify({event_type:'drive-index-updated'})}).getResponseCode()===204;}
function doGet(){return ContentService.createTextOutput(JSON.stringify(publishPublicJson())).setMimeType(ContentService.MimeType.JSON);}
function parsePost_(e){const raw=e&&e.postData&&e.postData.contents||''; if(!raw)return {}; try{return JSON.parse(raw);}catch(_){return e.parameter||{};}}
function safe_(value,max){return String(value||'').slice(0,max||500).replace(/[<>]/g,'').replace(/^[=+\-@]/,' ');}
function route_(categoryId){const sheet=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.routing); if(!sheet||sheet.getLastRow()<2)return {}; const rows=sheet.getDataRange().getValues(); const headers=rows.shift(); const idx=Object.fromEntries(headers.map((h,i)=>[h,i])); const row=rows.find(r=>String(r[idx.categoryId])===String(categoryId)&&String(r[idx.active]).toUpperCase()!=='N'); if(!row)return {}; return {recipientEmail:row[idx.recipientEmail]||prop_('INQUIRY_REPLY_TO_EMAIL'),ccEmail:row[idx.ccEmail]||'',owner:row[idx.owner]||'',sla:Number(row[idx.responseSlaHours]||48)};}
function handleInquiry(e){const body=parsePost_(e); if(body.website||Number(body.formStartedAt)&&Date.now()-Number(body.formStartedAt)<2500) throw new Error('spam'); const allowed=['name','company','role','email','phone','country','product','categoryId','gateId','documentId','claimId','currentUrl','requestType','targetDate','expectedVolume','budgetRange','meetingPreference','ndaRequested','message','consent','marketingConsent']; const clean={}; allowed.forEach(k=>clean[k]=safe_(body[k],k==='message'?3000:300)); if(!clean.name||!clean.company||!clean.email||clean.consent!=='true'||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean.email)) throw new Error('required'); const id='REQ-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Utilities.getUuid().slice(0,6).toUpperCase(); const route=route_(clean.categoryId); const summary=clean.company+'의 '+(clean.role||'담당자')+'가 '+(clean.categoryId||'협업')+' 상담을 요청했습니다. '+(clean.gateId?clean.gateId+' Gate 문맥이 연결되었습니다.':''); const sheet=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.inquiries); sheet.appendRow([id,new Date(),'NEW',clean.categoryId||'',clean.categoryId||'',clean.name,clean.company,clean.role||'',clean.email,clean.phone||'',clean.country||'',clean.product||'',clean.gateId||'',clean.documentId||'',clean.claimId||'',clean.currentUrl||'',clean.requestType||'',clean.targetDate||'',clean.expectedVolume||'',clean.budgetRange||'',clean.meetingPreference||'',clean.ndaRequested||'',clean.message||'',summary,clean.consent,clean.marketingConsent||'N','web',route.owner,new Date(Date.now()+(route.sla||48)*3600000),'', '']); sendInquiryNotifications({id,clean,route,summary}); writeAuditLog('inquiry',id); return {ok:true,requestId:id};}
function doPost(e){try{return ContentService.createTextOutput(JSON.stringify(handleInquiry(e))).setMimeType(ContentService.MimeType.JSON);}catch(err){writeAuditLog('inquiry-error',String(err.message||'unknown')); return ContentService.createTextOutput(JSON.stringify({ok:false,error:'문의 처리에 실패했습니다. 입력값을 확인하고 다시 시도해 주세요.'})).setMimeType(ContentService.MimeType.JSON);}}
function sendInquiryNotifications(item){const to=item.route.recipientEmail||prop_('ADMIN_NOTIFICATION_EMAIL'); const reply=prop_('INQUIRY_REPLY_TO_EMAIL')||to; if(to)MailApp.sendEmail({to,cc:item.route.ccEmail||'',subject:'[Master Index] 협업문의 '+item.id,body:item.summary+'\n\n접수번호: '+item.id+'\n회신 이메일: '+item.clean.email}); if(reply)MailApp.sendEmail({to:item.clean.email,replyTo:reply,subject:'문의 접수확인 '+item.id,body:'문의가 접수되었습니다.\n접수번호: '+item.id+'\n담당자가 영업일 기준 2일 이내 회신합니다.'});}
function sendInquiryNotificationsLegacy(){}
function writeSyncLog(action,status,message){const s=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.syncLog); if(s)s.appendRow([new Date(),action,status,message]);}
function writeAuditLog(action,message){const s=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.audit); if(s)s.appendRow([new Date(),action,message,Session.getActiveUser().getEmail()||'']);}
