const SHEETS = {project:'프로젝트대시보드', gates:'Gate관리', documents:'문서등록', experiments:'실험검증', risks:'리스크', roadmap:'로드맵', products:'제품파이프라인', policy:'공개정책', settings:'설정', technology:'기술요약', checklist:'자료체크리스트', claims:'Claim-Evidence', inquiries:'협업문의', routing:'문의라우팅', syncLog:'동기화로그', audit:'변경이력'};
const HEADERS = {documents:['id','title','category','summary','status','publicationLevel','publicationApproved','sourceType','version','modifiedAt','owner','gateIds','claimIds','language','publicUrl'], inquiries:['requestId','submittedAt','status','categoryId','categoryName','name','company','role','email','phone','country','product','gateId','documentId','claimId','currentUrl','requestType','targetDate','expectedVolume','budgetRange','meetingPreference','ndaRequested','message','generatedSummary','consent','marketingConsent','source','assignee','responseDueAt','notifiedAt','closedAt'], routing:['categoryId','categoryName','active','recipientEmail','ccEmail','owner','requiredFields','optionalFields','defaultSubject','responseSlaHours','confirmationTemplate','retentionDays']};
function prop_(key){return PropertiesService.getScriptProperties().getProperty(key)||'';}
function setupProject(){ensureSheetsAndHeaders();installAutomation();scanDriveAndUpsertDocuments();buildPublicIndex();}
function ensureSheetsAndHeaders(){const id=prop_('MASTER_SHEET_ID'); if(!id) throw new Error('MASTER_SHEET_ID is required'); const ss=SpreadsheetApp.openById(id); Object.values(SHEETS).forEach(name=>{const sheet=ss.getSheetByName(name)||ss.insertSheet(name); const headers=HEADERS[name]; if(headers&&!sheet.getLastRow()) sheet.getRange(1,1,1,headers.length).setValues([headers]);});}
function scanDriveAndUpsertDocuments(){const root=DriveApp.getFolderById(prop_('ROOT_FOLDER_ID')); const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const sheet=ss.getSheetByName(SHEETS.documents); const values=sheet.getDataRange().getValues(); const ids={}; values.slice(1).forEach((r,i)=>ids[r[0]=i+2]); const walk=(folder)=>{const files=folder.getFiles(); while(files.hasNext()){const f=files.next(); const id=f.getId(); const row=ids[id]||sheet.getLastRow()+1; const old=ids[id]?sheet.getRange(row,1,1,15).getValues()[0]:[]; const v=[id,f.getName(),old[2]||'미분류',old[3]||'자동등록 문서',old[4]||'active',old[5]||'RESTRICTED',old[6]||'N',f.getMimeType(),old[8]||'1',f.getLastUpdated(),old[10]||'',old[11]||'',old[12]||'',old[13]||'ko',old[14]||'']; sheet.getRange(row,1,1,v.length).setValues([v]);} const folders=folder.getFolders(); while(folders.hasNext()) walk(folders.next());}; walk(root); writeSyncLog('scanDriveAndUpsertDocuments','success','');}
function buildPublicIndex(){const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const docs=ss.getSheetByName(SHEETS.documents).getDataRange().getValues().slice(1).filter(r=>r[5]==='PUBLIC'&&r[6]==='Y').map(r=>({id:r[0],title:r[1],category:r[2],summary:r[3],status:r[4],publicationLevel:r[5],publicationApproved:r[6],sourceType:r[7],version:r[8],modifiedAt:r[9],owner:r[10],gateIds:String(r[11]||'').split(',').filter(Boolean),claimIds:String(r[12]||'').split(',').filter(Boolean),language:r[13]})); return {schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),source:{type:'Google Drive + Master Control',lastSyncedAt:new Date().toISOString()},documents:docs};}
function validatePublicIndex(index){if(!index||!Array.isArray(index.documents)) throw new Error('Invalid public index'); index.documents.forEach(d=>{if(d.publicationLevel!=='PUBLIC'||d.publicationApproved!=='Y'||d.publicUrl&&d.publicationLevel!=='PUBLIC') throw new Error('Publication boundary violation');}); return true;}
function publishPublicJson(){const index=buildPublicIndex(); validatePublicIndex(index); return JSON.stringify(index);}
function installAutomation(){const mins=Number(prop_('TRIGGER_MINUTES')||30); ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='scanDriveAndUpsertDocuments').forEach(t=>ScriptApp.deleteTrigger(t)); ScriptApp.newTrigger('scanDriveAndUpsertDocuments').timeBased().everyMinutes(Math.max(1,Math.min(60,mins))).create();}
function removeAutomation(){ScriptApp.getProjectTriggers().forEach(t=>ScriptApp.deleteTrigger(t));}
function sendGithubDispatch(){const pat=prop_('GITHUB_FINE_GRAINED_PAT'); if(!pat)return {ok:false,reason:'PAT not configured'}; const url='https://api.github.com/repos/'+prop_('GITHUB_OWNER')+'/'+prop_('GITHUB_REPO')+'/dispatches'; return UrlFetchApp.fetch(url,{method:'post',headers:{Authorization:'Bearer '+pat,Accept:'application/vnd.github+json'},contentType:'application/json',payload:JSON.stringify({event_type:'drive-index-updated'})}).getResponseCode()===204;}
function doGet(){return ContentService.createTextOutput(JSON.stringify(publishPublicJson())).setMimeType(ContentService.MimeType.JSON);}
function doPost(e){try{const body=JSON.parse(e.postData.contents||'{}'); const allowed=['name','company','role','email','phone','categoryId','gateId','documentId','claimId','message','consent']; const clean={}; allowed.forEach(k=>clean[k]=String(body[k]||'').slice(0,2000).replace(/^[=+\-@]/,' ')); if(!clean.name||!clean.company||!clean.email||clean.consent!=='true') throw new Error('Required fields missing'); const id='REQ-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss'); const sheet=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.inquiries); sheet.appendRow([id,new Date(),'NEW',clean.categoryId||'',clean.categoryId||'',clean.name,clean.company,clean.role||'',clean.email,clean.phone||'', '', '',clean.product||'',clean.gateId||'',clean.documentId||'',clean.claimId||'', '', '', '', '', '', '', clean.message||'', '상담 목적: '+(clean.categoryId||'미지정')+' / 현재 Gate: '+(clean.gateId||'없음'), 'Y','','web','',new Date()]); return ContentService.createTextOutput(JSON.stringify({ok:true,requestId:id})).setMimeType(ContentService.MimeType.JSON);}catch(err){return ContentService.createTextOutput(JSON.stringify({ok:false,error:'문의 처리에 실패했습니다.'})).setMimeType(ContentService.MimeType.JSON);}}
function sendInquiryNotifications(){} function writeSyncLog(action,status,message){const s=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.syncLog); if(s)s.appendRow([new Date(),action,status,message]);} function writeAuditLog(){writeSyncLog('audit','success','');}
