const SHEETS = {project:'프로젝트대시보드', gates:'Gate관리', documents:'문서등록', experiments:'실험검증', risks:'리스크', roadmap:'로드맵', products:'제품파이프라인', policy:'공개정책', settings:'설정', technology:'기술요약', checklist:'자료체크리스트', claims:'Claim-Evidence', inquiries:'협업문의', routing:'문의라우팅', syncLog:'동기화로그', audit:'변경이력'};
const HEADERS = {project:['metric','value','source','lastUpdated'],gates:['Gate ID','평가영역','필수 Gate','통과기준','상태','가중치(%)','담당','목표일','필요 증빙','증빙 파일 ID','공개 요약','공개여부','최근 업데이트','비고'],documents:['문서 ID','Drive file ID','폴더코드','문서분류','공개제목','원본파일명','연계 Gate','소유부서','공개등급','공개승인','상태','버전','태그','공개요약','수정일','Drive URL','개인정보점검','비고'],experiments:['id','title','stage','sop','batchSize','resultSummary','verificationStatus','evidenceIds','lastUpdated'],risks:['id','title','severity','impact','mitigation','owner','status','lastUpdated'],roadmap:['id','year','title','items','status','owner'],products:['id','name','market','stage','status','description','targetDate'],policy:['publicationLevel','publicationApproved','allowedFields','prohibitedFields','reviewer','reviewedAt'],settings:['key','value','description'],technology:['id','name','type','role','status','publicSummary'],checklist:['id','area','item','status','evidenceIds','owner'],claims:['Claim ID','영역','주장','주장수준','연계 증빙','증빙상태','추가 필요자료','공개 권고문구','담당','목표일','공개여부','비고'],inquiries:['requestId','submittedAt','status','categoryId','categoryName','name','company','role','email','phone','country','product','gateId','documentId','claimId','currentUrl','requestType','targetDate','expectedVolume','budgetRange','meetingPreference','ndaRequested','message','generatedSummary','consent','marketingConsent','source','assignee','responseDueAt','notifiedAt','closedAt'],routing:['categoryId','categoryName','active','recipientEmail','ccEmail','owner','requiredFields','optionalFields','defaultSubject','responseSlaHours','confirmationTemplate','retentionDays'],syncLog:['timestamp','action','status','message'],audit:['timestamp','action','message','actor']};
function prop_(key){return PropertiesService.getScriptProperties().getProperty(key)||'';}
const DRIVE_FOLDERS=['00_운영관리_웹인덱스','01_법인_지배구조_IP귀속','02_핵심기술_균주_특허','03_기술검증_재현성_분석','04_Scale-up_제조공정_원가','05_품질_QA_QC_규제','06_제품_시장_고객','07_ESG_바이오셀룰로오스_탄소','08_재무_KIFRS_내부통제','09_기술성평가_상장심사','10_투자_IR_데이터룸','99_원본_보관_비공개'];
function setupProject(){ensureSheetsAndHeaders();ensureDriveFolders_();installAutomation();scanDriveAndUpsertDocuments();buildPublicIndex();}
function ensureDriveFolders_(){const root=DriveApp.getFolderById(prop_('ROOT_FOLDER_ID')); DRIVE_FOLDERS.forEach(name=>{if(!root.getFoldersByName(name).hasNext()) root.createFolder(name);});}
function ensureSheetsAndHeaders(){const id=prop_('MASTER_SHEET_ID'); if(!id) throw new Error('MASTER_SHEET_ID is required'); const ss=SpreadsheetApp.openById(id); Object.values(SHEETS).forEach(name=>{const sheet=ss.getSheetByName(name)||ss.insertSheet(name); const headers=HEADERS[name]; if(headers&&!sheet.getLastRow()) sheet.getRange(1,1,1,headers.length).setValues([headers]);});}
function scanDriveAndUpsertDocuments(){const root=DriveApp.getFolderById(prop_('ROOT_FOLDER_ID')); const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const sheet=ss.getSheetByName(SHEETS.documents); const values=sheet.getDataRange().getValues(); const ids={}; values.slice(1).forEach((r,i)=>{if(r[1]) ids[String(r[1])]=i+2;}); const seen={}; const walk=(folder,folderPath)=>{const files=folder.getFiles(); while(files.hasNext()){const f=files.next(); const id=f.getId(); seen[id]=true; const row=ids[id]||sheet.getLastRow()+1; const old=ids[id]?sheet.getRange(row,1,1,18).getValues()[0]:[]; const docId=old[0]||'DOC-'+id.slice(0,8).toUpperCase(); const v=[docId,id,old[2]||folderPath,old[3]||'미분류',old[4]||f.getName(),f.getName(),old[6]||'',old[7]||'',old[8]||'RESTRICTED',old[9]||'N',old[10]||'원본등록',old[11]||1,old[12]||'',old[13]||'자동등록 문서',f.getLastUpdated(),old[15]||f.getUrl(),old[16]||'미검토',old[17]||'']; sheet.getRange(row,1,1,18).setValues([v]);} const folders=folder.getFolders(); while(folders.hasNext()){const child=folders.next(); walk(child,folderPath+'/'+child.getName());}}; walk(root,root.getName()); for(let i=2;i<=sheet.getLastRow();i++){const id=String(sheet.getRange(i,2).getValue()||''); if(id&&!seen[id]&&sheet.getRange(i,11).getValue()!=='ARCHIVED') sheet.getRange(i,11).setValue('MISSING');} writeSyncLog('scanDriveAndUpsertDocuments','success',''); writeAuditLog('drive-scan',Object.keys(seen).length+' files');}
function mapStatus_(value){const v=String(value||''); return v==='완료'?'complete':v==='진행중'?'in_progress':v==='차단'?'blocked':v==='보류'?'blocked':'not_started';}
function buildPublicIndex(){const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const docs=ss.getSheetByName(SHEETS.documents).getDataRange().getValues().slice(1).filter(r=>r[8]==='PUBLIC'&&r[9]==='Y').map(r=>({id:r[0],title:r[4],category:r[3],summary:r[13],status:r[10],publicationLevel:r[8],publicationApproved:r[9],sourceType:r[3],version:r[11],modifiedAt:r[14],owner:r[7],gateIds:String(r[6]||'').split(';').filter(Boolean),claimIds:[],tags:String(r[12]||'').split(';').filter(Boolean),language:'ko'})); const gateSheet=ss.getSheetByName(SHEETS.gates); const gates=gateSheet.getDataRange().getValues().slice(1).filter(r=>r[0]).map(r=>({id:r[0],area:r[1],title:r[2],description:r[2],passCriteria:r[3],status:mapStatus_(r[4]),weight:Number(r[5]||0),owner:r[6]||'',targetDate:r[7]||'',requiredEvidence:String(r[8]||'').split('·').filter(Boolean),publicSummary:r[10]||'',evidenceCount:String(r[9]||'').split('·').filter(Boolean).length,checklistProgress:mapStatus_(r[4])==='complete'?100:mapStatus_(r[4])==='in_progress'?50:0,lastUpdated:r[12]||''})); const claimSheet=ss.getSheetByName(SHEETS.claims); const claims=claimSheet.getDataRange().getValues().slice(1).filter(r=>r[0]&&r[10]==='Y').map(r=>({claimId:r[0],claim:r[2],claimType:r[3],evidenceLevel:r[3]==='특허 실시예'?'patent_application':'official_document',evidenceIds:String(r[4]||'').split(';').filter(Boolean),limitation:r[6]||'',verificationStatus:String(r[5]||'').indexOf('필요')>=0?'verification_required':'partially_verified',reviewer:r[8]||'',reviewedAt:r[9]||'',publicWording:r[7]||'',prohibitedWording:''})); const output={schemaVersion:'1.0.0',generatedAt:new Date().toISOString(),source:{type:'Google Drive + Master Control',lastSyncedAt:new Date().toISOString()},project:{targetListingYear:2030,decision:'Conditional GO'},readiness:{note:'내부 관리지표'},gates:gates,technology:{},claims:claims,documents:docs,experiments:[],risks:[],roadmap:[],products:[],esg:[],consultationCategories:[],publicationPolicy:{rule:'PUBLIC + Y only'},syncHealth:{mode:'apps-script',endpointConfigured:true,status:'published'}}; validatePublicIndex(output); return output;}
function validatePublicIndex(index){if(!index||!Array.isArray(index.documents)||!Array.isArray(index.gates)||index.gates.length!==10) throw new Error('Invalid public index or missing ten gates'); if(index.gates.reduce((sum,g)=>sum+Number(g.weight||0),0)!==100) throw new Error('Gate weights must total 100'); index.documents.forEach(d=>{if(d.publicationLevel!=='PUBLIC'||d.publicationApproved!=='Y'||d.publicUrl&&d.publicationLevel!=='PUBLIC') throw new Error('Publication boundary violation');}); return true;}
function publishPublicJson(){const index=buildPublicIndex(); validatePublicIndex(index); return JSON.stringify(index);}
function installAutomation(){const mins=Number(prop_('TRIGGER_MINUTES')||30); ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='scanDriveAndUpsertDocuments').forEach(t=>ScriptApp.deleteTrigger(t)); ScriptApp.newTrigger('scanDriveAndUpsertDocuments').timeBased().everyMinutes(Math.max(1,Math.min(60,mins))).create();}
function removeAutomation(){ScriptApp.getProjectTriggers().forEach(t=>ScriptApp.deleteTrigger(t));}
function sendGithubDispatch(){const pat=prop_('GITHUB_FINE_GRAINED_PAT'); if(!pat)return {ok:false,reason:'PAT not configured'}; const url='https://api.github.com/repos/'+prop_('GITHUB_OWNER')+'/'+prop_('GITHUB_REPO')+'/dispatches'; return UrlFetchApp.fetch(url,{method:'post',headers:{Authorization:'Bearer '+pat,Accept:'application/vnd.github+json'},contentType:'application/json',payload:JSON.stringify({event_type:'drive-index-updated'})}).getResponseCode()===204;}
function doGet(){return ContentService.createTextOutput(JSON.stringify(publishPublicJson())).setMimeType(ContentService.MimeType.JSON);}
function parsePost_(e){const raw=e&&e.postData&&e.postData.contents||''; if(!raw)return {}; try{return JSON.parse(raw);}catch(_){return e.parameter||{};}}
function safe_(value,max){return String(value||'').slice(0,max||500).replace(/[<>]/g,'').replace(/^[=+\-@]/,' ');}
function route_(categoryId){const sheet=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.routing); if(!sheet||sheet.getLastRow()<2)return {}; const rows=sheet.getDataRange().getValues(); const headers=rows.shift(); const idx=Object.fromEntries(headers.map((h,i)=>[h,i])); const row=rows.find(r=>String(r[idx.categoryId])===String(categoryId)&&String(r[idx.active]).toUpperCase()!=='N'); if(!row)return {}; return {recipientEmail:row[idx.recipientEmail]||prop_('INQUIRY_REPLY_TO_EMAIL'),ccEmail:row[idx.ccEmail]||'',owner:row[idx.owner]||'',sla:Number(row[idx.responseSlaHours]||48)};}
function handleInquiry(e){const body=parsePost_(e); if(body.website||Number(body.formStartedAt)&&Date.now()-Number(body.formStartedAt)<2500) throw new Error('spam'); const allowed=['name','company','role','email','phone','country','product','categoryId','gateId','documentId','claimId','currentUrl','requestType','targetDate','expectedVolume','budgetRange','meetingPreference','ndaRequested','message','consent','marketingConsent']; const clean={}; allowed.forEach(k=>clean[k]=safe_(body[k],k==='message'?3000:300)); if(!clean.name||!clean.company||!clean.email||clean.consent!=='true'||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean.email)) throw new Error('required'); const id='REQ-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Utilities.getUuid().slice(0,6).toUpperCase(); const route=route_(clean.categoryId); const summary=clean.company+'의 '+(clean.role||'담당자')+'가 '+(clean.categoryId||'협업')+' 상담을 요청했습니다. '+(clean.gateId?clean.gateId+' Gate 문맥이 연결되었습니다.':''); const sheet=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.inquiries); sheet.appendRow([id,new Date(),'NEW',clean.categoryId||'',clean.categoryId||'',clean.name,clean.company,clean.role||'',clean.email,clean.phone||'',clean.country||'',clean.product||'',clean.gateId||'',clean.documentId||'',clean.claimId||'',clean.currentUrl||'',clean.requestType||'',clean.targetDate||'',clean.expectedVolume||'',clean.budgetRange||'',clean.meetingPreference||'',clean.ndaRequested||'',clean.message||'',summary,clean.consent,clean.marketingConsent||'N','web',route.owner,new Date(Date.now()+(route.sla||48)*3600000),'', '']); sendInquiryNotifications({id,clean,route,summary}); writeAuditLog('inquiry',id); return {ok:true,requestId:id};}
function doPost(e){try{return ContentService.createTextOutput(JSON.stringify(handleInquiry(e))).setMimeType(ContentService.MimeType.JSON);}catch(err){writeAuditLog('inquiry-error',String(err.message||'unknown')); return ContentService.createTextOutput(JSON.stringify({ok:false,error:'문의 처리에 실패했습니다. 입력값을 확인하고 다시 시도해 주세요.'})).setMimeType(ContentService.MimeType.JSON);}}
function sendInquiryNotifications(item){const to=item.route.recipientEmail||prop_('ADMIN_NOTIFICATION_EMAIL'); const reply=prop_('INQUIRY_REPLY_TO_EMAIL')||to; if(to)MailApp.sendEmail({to,cc:item.route.ccEmail||'',subject:'[Master Index] 협업문의 '+item.id,body:item.summary+'\n\n접수번호: '+item.id+'\n회신 이메일: '+item.clean.email}); if(reply)MailApp.sendEmail({to:item.clean.email,replyTo:reply,subject:'문의 접수확인 '+item.id,body:'문의가 접수되었습니다.\n접수번호: '+item.id+'\n담당자가 영업일 기준 2일 이내 회신합니다.'});}
function sendInquiryNotificationsLegacy(){}
function writeSyncLog(action,status,message){const s=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.syncLog); if(s)s.appendRow([new Date(),action,status,message]);}
function writeAuditLog(action,message){const s=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.audit); if(s)s.appendRow([new Date(),action,message,Session.getActiveUser().getEmail()||'']);}

// Public-feed override: reads the live Korean Master Control headers by name so
// column additions/reordering do not silently change the publication contract.
function publicRows_(ss,name){const sheet=ss.getSheetByName(name); if(!sheet||sheet.getLastRow()<2)return {headers:[],rows:[]}; const values=sheet.getDataRange().getValues(); return {headers:values[0].map(String),rows:values.slice(1).filter(r=>r.some(v=>v!==''&&v!==null))};}
function publicCol_(headers,row,name){const i=headers.indexOf(name); return i<0?'':row[i];}
function publicList_(value){return String(value||'').split(/[;,·\\n]/).map(v=>String(v).trim()).filter(Boolean);}
function publicApproved_(headers,row){return String(publicCol_(headers,row,'공개여부')).toUpperCase()==='Y';}
function buildPublicIndex(){
  const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const now=new Date().toISOString();
  const d=publicRows_(ss,SHEETS.documents); const docs=d.rows.filter(r=>publicCol_(d.headers,r,'공개등급')==='PUBLIC'&&String(publicCol_(d.headers,r,'공개승인')).toUpperCase()==='Y'&&String(publicCol_(d.headers,r,'개인정보점검')).indexOf('완료')>=0).map(r=>({id:publicCol_(d.headers,r,'문서 ID'),title:publicCol_(d.headers,r,'공개제목')||publicCol_(d.headers,r,'원본파일명'),category:publicCol_(d.headers,r,'문서분류'),summary:publicCol_(d.headers,r,'공개요약'),status:publicCol_(d.headers,r,'상태'),publicationLevel:'PUBLIC',publicationApproved:'Y',sourceType:publicCol_(d.headers,r,'문서분류'),version:publicCol_(d.headers,r,'버전'),modifiedAt:publicCol_(d.headers,r,'수정일'),owner:publicCol_(d.headers,r,'소유부서'),gateIds:publicList_(publicCol_(d.headers,r,'연계 Gate')),claimIds:[],tags:publicList_(publicCol_(d.headers,r,'태그')),language:'ko'}));
  const g=publicRows_(ss,SHEETS.gates); const gates=g.rows.filter(r=>publicCol_(g.headers,r,'Gate ID')).map(r=>({id:publicCol_(g.headers,r,'Gate ID'),area:publicCol_(g.headers,r,'평가영역'),title:publicCol_(g.headers,r,'필수 Gate'),description:publicCol_(g.headers,r,'필수 Gate'),passCriteria:publicCol_(g.headers,r,'통과기준'),status:mapStatus_(publicCol_(g.headers,r,'상태')),weight:Number(publicCol_(g.headers,r,'가중치(%)')||0),owner:publicCol_(g.headers,r,'담당'),targetDate:publicCol_(g.headers,r,'목표일'),requiredEvidence:publicList_(publicCol_(g.headers,r,'필요 증빙')),evidenceCount:publicList_(publicCol_(g.headers,r,'증빙 파일 ID')).length,checklistProgress:mapStatus_(publicCol_(g.headers,r,'상태'))==='complete'?100:mapStatus_(publicCol_(g.headers,r,'상태'))==='in_progress'?50:0,publicSummary:publicCol_(g.headers,r,'공개 요약'),lastUpdated:publicCol_(g.headers,r,'최근 업데이트')}));
  const c=publicRows_(ss,SHEETS.claims); const claims=c.rows.filter(r=>publicCol_(c.headers,r,'Claim ID')&&publicApproved_(c.headers,r)).map(r=>({claimId:publicCol_(c.headers,r,'Claim ID'),claim:publicCol_(c.headers,r,'주장'),claimType:publicCol_(c.headers,r,'주장수준'),evidenceLevel:publicCol_(c.headers,r,'주장수준')==='특허 실시예'?'patent_application':'official_document',evidenceIds:publicList_(publicCol_(c.headers,r,'연계 증빙')),limitation:publicCol_(c.headers,r,'추가 필요자료'),verificationStatus:String(publicCol_(c.headers,r,'증빙상태')).indexOf('필요')>=0?'verification_required':'partially_verified',reviewer:publicCol_(c.headers,r,'담당'),reviewedAt:publicCol_(c.headers,r,'목표일'),publicWording:publicCol_(c.headers,r,'공개 권고문구'),prohibitedWording:''}));
  const t=publicRows_(ss,SHEETS.technology); const technology=t.rows.filter(r=>publicApproved_(t.headers,r)).map(r=>({id:publicCol_(t.headers,r,'ID'),name:publicCol_(t.headers,r,'명칭·주장'),type:publicCol_(t.headers,r,'구분'),role:publicCol_(t.headers,r,'값·역할'),status:publicCol_(t.headers,r,'검증 상태·필요자료'),publicSummary:publicCol_(t.headers,r,'공개 문구'),gateId:publicCol_(t.headers,r,'연계 Gate')}));
  const e=publicRows_(ss,SHEETS.experiments); const experiments=e.rows.filter(r=>publicApproved_(e.headers,r)).map(r=>({id:publicCol_(e.headers,r,'시험 ID'),gateId:publicCol_(e.headers,r,'연계 Gate'),title:publicCol_(e.headers,r,'시험명'),hypothesis:publicCol_(e.headers,r,'검증 가설'),controls:publicCol_(e.headers,r,'필수 대조군·설계'),kpi:publicCol_(e.headers,r,'주요 KPI'),acceptanceCriteria:publicCol_(e.headers,r,'권고 수용기준'),status:publicCol_(e.headers,r,'상태'),externalValidation:publicCol_(e.headers,r,'외부검증')}));
  const r=publicRows_(ss,SHEETS.risks); const risks=r.rows.filter(row=>publicApproved_(r.headers,row)).map(row=>({id:publicCol_(r.headers,row,'리스크 ID'),title:publicCol_(r.headers,row,'리스크'),severity:publicCol_(r.headers,row,'등급'),impact:publicCol_(r.headers,row,'영향도(1-5)'),mitigation:publicCol_(r.headers,row,'완화조치'),owner:publicCol_(r.headers,row,'담당'),status:publicCol_(r.headers,row,'상태')}));
  const rm=publicRows_(ss,SHEETS.roadmap); const roadmap=rm.rows.filter(row=>publicApproved_(rm.headers,row)).map(row=>({id:publicCol_(rm.headers,row,'마일스톤 ID'),year:String(publicCol_(rm.headers,row,'시작일')).slice(0,4),title:publicCol_(rm.headers,row,'핵심목표'),items:publicList_(publicCol_(rm.headers,row,'주요 산출물')),status:publicCol_(rm.headers,row,'상태'),progress:Number(publicCol_(rm.headers,row,'진척률(%)')||0),publicSummary:publicCol_(rm.headers,row,'공개요약')}));
  const p=publicRows_(ss,SHEETS.products); const products=p.rows.filter(row=>publicApproved_(p.headers,row)).map(row=>({id:publicCol_(p.headers,row,'제품 ID'),name:publicCol_(p.headers,row,'제품 포지셔닝'),market:publicCol_(p.headers,row,'시장'),stage:publicCol_(p.headers,row,'현재 단계'),status:publicCol_(p.headers,row,'상태'),description:publicCol_(p.headers,row,'상장 스토리 역할'),targetDate:publicCol_(p.headers,row,'목표 상용화')}));
  const s=publicRows_(ss,SHEETS.settings); const setting=key=>{const row=s.rows.find(x=>String(publicCol_(s.headers,x,'key')||publicCol_(s.headers,x,'설정키'))===key); return row?publicCol_(s.headers,row,'value')||publicCol_(s.headers,row,'설정값'):'';};
  const output={schemaVersion:'1.0.0',generatedAt:now,source:{type:'Google Drive + Master Control',lastSyncedAt:now},project:{name:setting('PROJECT_NAME')||'신규 제조법인 기술특례상장 Master Web Index',tagline:'Evidence-first technology listing readiness',targetListingYear:Number(setting('TARGET_LISTING_YEAR')||2030),decision:setting('PROJECT_DECISION')||'CONDITIONAL_GO'},readiness:{score:0,label:'live sheet',note:'공개 승인된 데이터만 표시'},gates:gates,technology:technology,claims:claims,documents:docs,experiments:experiments,risks:risks,roadmap:roadmap,products:products,esg:[],consultationCategories:[],publicationPolicy:{rule:'PUBLIC + Y + 개인정보점검 완료 only',levels:['PUBLIC','RESTRICTED','CONFIDENTIAL']},syncHealth:{mode:'apps-script',endpointConfigured:true,status:'published'}};
  validatePublicIndex(output); return output;
}
function doGet(){return ContentService.createTextOutput(publishPublicJson()).setMimeType(ContentService.MimeType.JSON);}

// Final live-sheet contract: the functions below supersede the scaffold above
// and are intentionally header-driven so the Korean control workbook remains
// the source of truth when columns move or new rows are added.
function mapStatus_(value){const v=String(value||'').replace(/\s/g,''); if(v==='완료')return 'complete'; if(v==='진행중')return 'in_progress'; if(v==='차단'||v==='보류')return 'blocked'; return 'not_started';}
function dashboardMetric_(ss,label){const sheet=ss.getSheetByName(SHEETS.project); if(!sheet)return ''; const rows=sheet.getDataRange().getValues(); for(const row of rows){for(let i=0;i<row.length;i++){if(String(row[i]||'').trim()===label)return row[i+1]||'';}} return '';}
function settingValue_(ss,key){const sheet=ss.getSheetByName(SHEETS.settings); if(!sheet)return ''; const rows=sheet.getDataRange().getValues(); for(const row of rows.slice(1)){const k=String(row[0]||'').trim(); if(k===key)return row[1]||'';} return '';}
function consultationCategories_(){return [
  {id:'ipo',name:'기술특례상장·기술성평가',description:'Gate·기술성평가·데이터룸 협업'},
  {id:'advisor',name:'IPO 주관사·회계·법무',description:'상장 구조·회계·법률 실사'},
  {id:'investment',name:'투자·사업제휴',description:'투자 검토·공동사업·전략적 제휴'},
  {id:'patent',name:'특허·균주·라이선스',description:'특허·균주·공동개발·라이선스'},
  {id:'scaleup',name:'발효 Scale-up·CDO·OEM',description:'공정이전·파일럿·제조 파트너십'},
  {id:'quality',name:'분석·시험·품질검증',description:'분석법·외부시험·QA/QC 검증'},
  {id:'human',name:'휴먼그레이드 GABA',description:'식품·건강기능식품 원료 상담'},
  {id:'feed',name:'사료용 GABA',description:'동물영양·사료 원료 상담'},
  {id:'cosmetic',name:'코스메틱 소재',description:'화장품 소재·OEM/ODM 상담'},
  {id:'agriculture',name:'농업·비료용 소재',description:'농업·비료·스마트팜 응용 상담'},
  {id:'esg',name:'바이오셀룰로오스·ESG·탄소',description:'순환소재·LCA·MRV 연구 상담'},
  {id:'dataroom',name:'자료열람·데이터룸',description:'공개 범위·자료열람 요청'},
  {id:'other',name:'기타 협업',description:'기타 기술·제조·사업 협업'}
];}
function buildPublicIndex(){
  const ss=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')); const now=new Date().toISOString();
  const d=publicRows_(ss,SHEETS.documents); const docs=d.rows.filter(r=>publicCol_(d.headers,r,'공개등급')==='PUBLIC'&&String(publicCol_(d.headers,r,'공개승인')).toUpperCase()==='Y'&&String(publicCol_(d.headers,r,'개인정보점검')).indexOf('완료')>=0).map(r=>({id:publicCol_(d.headers,r,'문서 ID'),title:publicCol_(d.headers,r,'공개제목')||publicCol_(d.headers,r,'원본파일명'),category:publicCol_(d.headers,r,'문서분류'),summary:publicCol_(d.headers,r,'공개요약'),status:publicCol_(d.headers,r,'상태'),publicationLevel:'PUBLIC',publicationApproved:'Y',sourceType:publicCol_(d.headers,r,'문서분류'),version:publicCol_(d.headers,r,'버전'),modifiedAt:publicCol_(d.headers,r,'수정일'),owner:publicCol_(d.headers,r,'소유부서'),gateIds:publicList_(publicCol_(d.headers,r,'연계 Gate')),claimIds:[],tags:publicList_(publicCol_(d.headers,r,'태그')),language:'ko'}));
  const g=publicRows_(ss,SHEETS.gates); const gates=g.rows.filter(r=>publicCol_(g.headers,r,'Gate ID')).map(r=>({id:publicCol_(g.headers,r,'Gate ID'),area:publicCol_(g.headers,r,'평가영역'),title:publicCol_(g.headers,r,'필수 Gate'),description:publicCol_(g.headers,r,'필수 Gate'),passCriteria:publicCol_(g.headers,r,'통과기준'),status:mapStatus_(publicCol_(g.headers,r,'상태')),weight:Number(publicCol_(g.headers,r,'가중치(%)')||0),owner:publicCol_(g.headers,r,'담당'),targetDate:publicCol_(g.headers,r,'목표일'),requiredEvidence:publicList_(publicCol_(g.headers,r,'필요 증빙')),evidenceCount:publicList_(publicCol_(g.headers,r,'증빙 파일 ID')).length,checklistProgress:mapStatus_(publicCol_(g.headers,r,'상태'))==='complete'?100:mapStatus_(publicCol_(g.headers,r,'상태'))==='in_progress'?50:0,publicSummary:publicCol_(g.headers,r,'공개 요약'),lastUpdated:publicCol_(g.headers,r,'최근 업데이트')}));
  const c=publicRows_(ss,SHEETS.claims); const claims=c.rows.filter(r=>publicCol_(c.headers,r,'Claim ID')&&publicApproved_(c.headers,r)).map(r=>({claimId:publicCol_(c.headers,r,'Claim ID'),claim:publicCol_(c.headers,r,'주장'),claimType:publicCol_(c.headers,r,'주장수준'),evidenceLevel:publicCol_(c.headers,r,'주장수준')==='특허 실시예'?'patent_application':'official_document',evidenceIds:publicList_(publicCol_(c.headers,r,'연계 증빙')),limitation:publicCol_(c.headers,r,'추가 필요자료'),verificationStatus:String(publicCol_(c.headers,r,'증빙상태')).indexOf('필요')>=0?'verification_required':'partially_verified',reviewer:publicCol_(c.headers,r,'담당'),reviewedAt:publicCol_(c.headers,r,'목표일'),publicWording:publicCol_(c.headers,r,'공개 권고문구'),prohibitedWording:''}));
  const t=publicRows_(ss,SHEETS.technology); const techRows=t.rows.filter(r=>publicApproved_(t.headers,r)); const technology={strains:techRows.filter(r=>publicCol_(t.headers,r,'구분')==='균주').map(r=>publicCol_(t.headers,r,'명칭·주장')+' · '+publicCol_(t.headers,r,'단위·수탁번호')).filter(Boolean),patents:techRows.filter(r=>publicCol_(t.headers,r,'구분')==='핵심증빙'&&String(publicCol_(t.headers,r,'명칭·주장')).indexOf('특허')>=0).map(r=>publicCol_(t.headers,r,'명칭·주장')).filter(Boolean),process:techRows.filter(r=>publicCol_(t.headers,r,'구분')==='플랫폼단계').map(r=>publicCol_(t.headers,r,'공개 문구')).filter(Boolean)};
  const e=publicRows_(ss,SHEETS.experiments); const experiments=e.rows.filter(r=>publicApproved_(e.headers,r)).map(r=>({id:publicCol_(e.headers,r,'시험 ID'),gateId:publicCol_(e.headers,r,'연계 Gate'),title:publicCol_(e.headers,r,'시험명'),hypothesis:publicCol_(e.headers,r,'검증 가설'),controls:publicCol_(e.headers,r,'필수 대조군·설계'),kpi:publicCol_(e.headers,r,'주요 KPI'),acceptanceCriteria:publicCol_(e.headers,r,'권고 수용기준'),status:publicCol_(e.headers,r,'상태'),externalValidation:publicCol_(e.headers,r,'외부검증')}));
  const r=publicRows_(ss,SHEETS.risks); const risks=r.rows.filter(row=>publicApproved_(r.headers,row)).map(row=>({id:publicCol_(r.headers,row,'리스크 ID'),title:publicCol_(r.headers,row,'리스크'),severity:publicCol_(r.headers,row,'등급'),impact:publicCol_(r.headers,row,'영향도(1-5)'),mitigation:publicCol_(r.headers,row,'완화조치'),owner:publicCol_(r.headers,row,'담당'),status:publicCol_(r.headers,row,'상태')}));
  const rm=publicRows_(ss,SHEETS.roadmap); const roadmap=rm.rows.filter(row=>publicApproved_(rm.headers,row)).map(row=>({id:publicCol_(rm.headers,row,'마일스톤 ID'),year:String(publicCol_(rm.headers,row,'시작일')).slice(0,4),title:publicCol_(rm.headers,row,'핵심목표'),items:publicList_(publicCol_(rm.headers,row,'주요 산출물')),status:publicCol_(rm.headers,row,'상태'),progress:Number(publicCol_(rm.headers,row,'진척률(%)')||0),publicSummary:publicCol_(rm.headers,row,'공개요약')}));
  const p=publicRows_(ss,SHEETS.products); const products=p.rows.filter(row=>publicApproved_(p.headers,row)).map(row=>({id:publicCol_(p.headers,row,'제품 ID'),name:publicCol_(p.headers,row,'제품 포지셔닝'),market:publicCol_(p.headers,row,'시장'),stage:publicCol_(p.headers,row,'현재 단계'),status:publicCol_(p.headers,row,'상태'),description:publicCol_(p.headers,row,'상장 스토리 역할'),targetDate:publicCol_(p.headers,row,'목표 상용화')}));
  const checklistRows=publicRows_(ss,SHEETS.checklist); const checklist=checklistRows.rows.filter(row=>publicApproved_(checklistRows.headers,row)).map(row=>({id:publicCol_(checklistRows.headers,row,'자료 ID'),area:publicCol_(checklistRows.headers,row,'분류'),item:publicCol_(checklistRows.headers,row,'필수자료'),gateIds:publicList_(publicCol_(checklistRows.headers,row,'연계 Gate')),status:publicCol_(checklistRows.headers,row,'상태'),publicSummary:publicCol_(checklistRows.headers,row,'공개 요약')}));
  const readinessText=String(dashboardMetric_(ss,'내부 준비도')||'').replace('%',''); const readinessScore=Number(readinessText)||gates.reduce((sum,g)=>sum+Number(g.weight||0)*(g.status==='complete'?1:g.status==='in_progress'?.5:0),0);
  const esg=products.filter(row=>String(row.market).indexOf('ESG')>=0).map(row=>row.name+' · '+row.description);
  const output={schemaVersion:'1.0.0',generatedAt:now,source:{type:'Google Drive + Master Control',lastSyncedAt:now},project:{name:settingValue_(ss,'PROJECT_NAME')||'신규 제조법인 기술특례상장 Master Web Index',tagline:'Precision-Fermented GABA Biomaterials Platform',targetListingYear:Number(settingValue_(ss,'TARGET_LISTING_YEAR')||2030),decision:settingValue_(ss,'PROJECT_DECISION')||'CONDITIONAL_GO'},readiness:{score:readinessScore,label:'내부 준비도',note:'공식 기술평가 등급이 아닌 내부 관리지표입니다.'},gates:gates,technology:technology,claims:claims,documents:docs,experiments:experiments,risks:risks,roadmap:roadmap,products:products,esg:esg,checklist:checklist,consultationCategories:consultationCategories_(),publicationPolicy:{rule:'PUBLIC + Y + 개인정보점검 완료 only',levels:['PUBLIC','RESTRICTED','CONFIDENTIAL']},syncHealth:{mode:'apps-script',endpointConfigured:true,status:'published'}};
  validatePublicIndex(output); return output;
}
function handleInquiry(e){const body=parsePost_(e); if(body.website||Number(body.formStartedAt)&&Date.now()-Number(body.formStartedAt)<2500)throw new Error('spam'); const allowed=['name','company','role','email','phone','country','product','categoryId','categoryName','gateId','documentId','claimId','currentUrl','requestType','targetDate','expectedVolume','budgetRange','meetingPreference','ndaRequested','message','consent','marketingConsent']; const clean={}; allowed.forEach(k=>clean[k]=safe_(body[k],k==='message'?3000:300)); if(!clean.name||!clean.company||!clean.email||clean.consent!=='true'||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean.email))throw new Error('required'); const normalizedEmail=clean.email.toLowerCase(); const cacheKey='inquiry_'+Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.MD5,normalizedEmail)).slice(0,80); const cache=CacheService.getScriptCache(); if(cache.get(cacheKey))throw new Error('duplicate'); cache.put(cacheKey,'1',3600); const id='REQ-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Utilities.getUuid().slice(0,6).toUpperCase(); const route=route_(clean.categoryId); const categoryName=clean.categoryName||clean.categoryId||'협업'; const summary=clean.company+'의 '+(clean.role||'담당자')+'가 '+categoryName+' 상담을 요청했습니다. '+(clean.gateId?clean.gateId+' Gate 문맥이 연결되었습니다.':''); const sheet=SpreadsheetApp.openById(prop_('MASTER_SHEET_ID')).getSheetByName(SHEETS.inquiries); sheet.appendRow([id,new Date(),'NEW',clean.categoryId||'',categoryName,clean.name,clean.company,clean.role||'',normalizedEmail,clean.phone||'',clean.country||'',clean.product||'',clean.gateId||'',clean.documentId||'',clean.claimId||'',clean.currentUrl||'',clean.requestType||'',clean.targetDate||'',clean.expectedVolume||'',clean.budgetRange||'',clean.meetingPreference||'',clean.ndaRequested||'',clean.message||'',summary,clean.consent,clean.marketingConsent||'N','web',route.owner,new Date(Date.now()+(route.sla||48)*3600000),'','']); sendInquiryNotifications({id,clean,route,summary}); writeAuditLog('inquiry',id); return {ok:true,requestId:id};}
function doPost(e){try{return ContentService.createTextOutput(JSON.stringify(handleInquiry(e))).setMimeType(ContentService.MimeType.JSON);}catch(err){writeAuditLog('inquiry-error',String(err.message||'unknown')); return ContentService.createTextOutput(JSON.stringify({ok:false,error:'문의 처리에 실패했습니다. 입력값과 중복 제출 여부를 확인해 주세요.'})).setMimeType(ContentService.MimeType.JSON);}}
