import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowUpRight, Beaker, BookOpen, Boxes, Building2, ChevronRight, ClipboardCheck, Database, FileCheck2, FlaskConical, GitBranch, Handshake, Leaf, Menu, Search, ShieldCheck, Target, X} from 'lucide-react';
import data from './data/master-index.json';
import type {MasterIndex, Section, Gate} from './types';
import './styles.css';

const model = data as MasterIndex;
const nav: {id:Section; label:string; icon:React.ElementType}[] = [
  {id:'overview',label:'종합현황',icon:Activity},{id:'technology',label:'핵심기술',icon:Beaker},{id:'gates',label:'필수 Gate',icon:Target},{id:'evidence',label:'증빙자료',icon:FileCheck2},{id:'experiments',label:'실험·검증',icon:FlaskConical},{id:'scaleup',label:'Scale-up·제조',icon:Boxes},{id:'products',label:'제품·시장',icon:Building2},{id:'esg',label:'ESG·바이오셀룰로오스',icon:Leaf},{id:'finance',label:'재무·지배구조',icon:ShieldCheck},{id:'roadmap',label:'로드맵',icon:GitBranch},{id:'risks',label:'리스크',icon:ClipboardCheck},{id:'consultation',label:'협업·상담',icon:Handshake}
];
const statusLabel:Record<string,string>={complete:'완료',in_progress:'진행 중',not_started:'미착수',blocked:'차단'};
const categoryOptions=[
 {id:'ipo',name:'기술특례상장·기술성평가',description:'Gate·기술성평가·데이터룸 협업'}, {id:'advisor',name:'IPO 주관사·회계·법무',description:'상장 구조·회계·법률 실사'}, {id:'investment',name:'투자·사업제휴',description:'투자 검토·공동사업·전략적 제휴'}, {id:'patent',name:'특허·균주·라이선스',description:'특허·균주·공동개발·라이선스'}, {id:'scaleup',name:'발효 Scale-up·CDO·OEM',description:'공정이전·파일럿·제조 파트너십'}, {id:'quality',name:'분석·시험·품질검증',description:'분석법·외부시험·QA/QC 검증'}, {id:'human',name:'휴먼그레이드 GABA',description:'식품·건강기능식품 원료 상담'}, {id:'feed',name:'사료용 GABA',description:'동물영양·사료 원료 상담'}, {id:'cosmetic',name:'코스메틱 소재',description:'화장품 소재·OEM/ODM 상담'}, {id:'agriculture',name:'농업·비료용 소재',description:'농업·비료·스마트팜 응용 상담'}, {id:'esg',name:'바이오셀룰로오스·ESG·탄소',description:'순환소재·LCA·MRV 연구 상담'}, {id:'dataroom',name:'자료열람·데이터룸',description:'공개 범위·자료열람 요청'}, {id:'other',name:'기타 협업',description:'기타 기술·제조·사업 협업'}
];
type SearchHit={kind:string;id:string;label:string;meta:string;section:Section;gate?:Gate};
const categoryQuestions:Record<string,string>={
 ipo:'준비 중인 상장·기술성평가 과제와 필요한 협업 범위를 알려주세요.',
 advisor:'필요한 주관사·회계·법무·PMO 지원과 희망 일정을 알려주세요.',
 investment:'투자 또는 사업제휴 검토 목적과 필요한 자료를 알려주세요.',
 patent:'관심 특허·균주·라이선스 범위와 협업 형태를 알려주세요.',
 scaleup:'목표 배치 규모·공정 단계·필요한 제조 파트너 범위를 알려주세요.',
 quality:'필요한 분석·시험·품질·규제 검증 항목을 알려주세요.',
 human:'관심 있는 휴먼 뉴트리션 제품과 목표 규격을 알려주세요.',
 feed:'관심 있는 사료·축산 적용과 목표 제품 조건을 알려주세요.',
 cosmetic:'관심 있는 코스메틱 소재·제형·OEM/ODM 범위를 알려주세요.',
 agriculture:'관심 있는 농업·작물 적용과 실증 조건을 알려주세요.',
 esg:'관심 있는 ESG·바이오셀룰로오스·LCA/MRV 과제를 알려주세요.',
 dataroom:'열람이 필요한 자료·Claim·Gate와 사용 목적을 알려주세요.',
 other:'협업 목적과 필요한 기술·제조·사업 지원을 알려주세요.'
};
function routeFromLocation():{section:Section;gate?:Gate}{const raw=window.location.hash.replace(/^#\/?/,''); const [path,query='']=raw.split('?'); const gate=path.match(/^gates\/(G\d+)$/i)?.[1]?.toUpperCase(); const sectionMap:Record<string,Section>={gates:'gates',technology:'technology',documents:'evidence',products:'products',consultation:'consultation'}; const section=sectionMap[path.split('/')[0]]||'overview'; const queryGate=new URLSearchParams(query).get('gate')?.toUpperCase(); return {section,gate:model.gates.find(g=>g.id===(gate||queryGate))};}
function App(){
 const initialRoute=routeFromLocation(); const [section,setSection]=useState<Section>(initialRoute.section); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(''); const [selectedGate,setSelectedGate]=useState<Gate|null>(initialRoute.gate||null); const [consult,setConsult]=useState(false); const [consultContext,setConsultContext]=useState<string|undefined>(initialRoute.gate?.id); const [consultCategory,setConsultCategory]=useState('scaleup');
 const openConsult=(category='scaleup',context?:string)=>{setConsultCategory(category);if(context!==undefined)setConsultContext(context);setConsult(true)};
 useEffect(()=>{const sync=()=>{const route=routeFromLocation();setSection(route.section);if(route.gate)setSelectedGate(route.gate)};window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 const filteredGates=useMemo(()=>model.gates.filter(g=>`${g.id} ${g.title} ${g.area}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const searchHits=useMemo<SearchHit[]>(()=>{const q=query.trim().toLowerCase(); if(!q)return []; const hit=(kind:string,id:string,label:string,meta:string,section:Section,gate?:Gate):SearchHit=>({kind,id,label,meta,section,gate}); return [...model.gates.map(g=>hit('Gate',g.id,g.title,`${g.id} · ${g.area}`, 'gates',g)),...model.documents.map(d=>hit('자료',d.id,d.title,`${d.id} · ${d.category}`,'evidence')),...model.claims.map(c=>hit('Claim',c.claimId,c.publicWording,`${c.claimId} · ${c.verificationStatus}`,'evidence')),...model.products.map(p=>hit('제품',p.id,p.name,`${p.id} · ${p.market}`,'products')),...model.experiments.map((e:any)=>hit('실험',String(e.id||''),String(e.title||''),`${e.id||''} · ${e.status||''}`,'experiments'))].filter(x=>`${x.id} ${x.label} ${x.meta}`.toLowerCase().includes(q)).slice(0,8)},[query]);
 const selectHit=(hit:SearchHit)=>{setQuery('');setMobile(false);if(hit.gate){setSelectedGate(hit.gate);setSection('gates');window.location.hash='/gates/'+hit.gate.id}else{setSection(hit.section);window.location.hash='/'+hit.section}};
 const go=(id:Section)=>{setSection(id);setMobile(false);window.location.hash=id==='overview'?'':'/'+id;window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="app-shell">
  <aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><div className="brand-mark">N</div><div><strong>MASTER INDEX</strong><span>기술특례상장 준비</span></div><button className="close-nav" onClick={()=>setMobile(false)} aria-label="메뉴 닫기"><X size={18}/></button></div><div className="nav-group"><small>OPERATING SYSTEM</small>{nav.map(({id,label,icon:Icon})=><button key={id} className={section===id?'active':''} onClick={()=>go(id)}><Icon size={17}/><span>{label}</span>{id==='gates'&&<b>10</b>}</button>)}</div><div className="sidebar-bottom"><div className="sync-dot"/><div><small>데이터 상태</small><strong>승인 스냅샷</strong></div></div></aside>
  {mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setMobile(true)} aria-label="메뉴 열기"><Menu size={20}/></button><div className="crumb">2030 상장 준비 <ChevronRight size={14}/> {nav.find(n=>n.id===section)?.label ?? '종합현황'}</div><div className="top-actions"><div className="search"><Search size={16}/><input aria-label="Gate 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Gate, 자료 검색"/></div><span className="env"><i/>PUBLIC VIEW</span></div></header>
   <div className="content"><div className="page-head"><div><p className="kicker">CONDITIONAL GO · 2030 LISTING ROADMAP</p><h1>{section==='overview'?'기술특례상장 준비 현황':nav.find(n=>n.id===section)?.label}</h1><p className="subhead">Precision-Fermented GABA Biomaterials Platform <span>·</span> 공개 승인 데이터 기준</p></div><button className="primary" onClick={()=>openConsult('dataroom')}>협업 문의 시작 <ArrowUpRight size={16}/></button></div>{searchHits.length>0&&<SearchResults hits={searchHits} onSelect={selectHit}/>} 
    {section==='overview'&&<Overview model={model} onGate={(g)=>{setSelectedGate(g);setSection('gates');window.location.hash='/gates/'+g.id}} onConsult={()=>openConsult('dataroom')}/>} {section==='gates'&&<Gates gates={filteredGates} onGate={(g)=>{setSelectedGate(g);window.location.hash='/gates/'+g.id}}/>} {section==='technology'&&<Technology model={model}/>} {section==='evidence'&&<Evidence model={model}/>} {section==='products'&&<Products model={model} onConsult={(id)=>openConsult('human',id)}/>} {section==='roadmap'&&<Roadmap model={model}/>} {section==='risks'&&<Risks model={model}/>} {section==='consultation'&&<ConsultationPage onOpen={(id)=>openConsult(id)}/>} {['experiments','scaleup','esg','finance'].includes(section)&&<Generic section={section} model={model}/>}<footer><span>Master Web Index · v{model.schemaVersion}</span><span>마지막 승인 동기화 {model.source.lastSyncedAt.slice(0,10)} · {model.syncHealth.status}</span></footer></div>
  </main>{selectedGate&&<GateDrawer gate={selectedGate} onClose={()=>setSelectedGate(null)} onConsult={()=>{setConsultContext(selectedGate.id);setConsultCategory('scaleup');setSelectedGate(null);setConsult(true)}}/>}{consult&&<ConsultationV2 key={`${consultCategory}-${consultContext||''}`} onClose={()=>setConsult(false)} context={consultContext} initialCategory={consultCategory}/>}</div>
}
function Metric({label,value,note,accent=false}:{label:string;value:string;note:string;accent?:boolean}){return <div className={`metric ${accent?'accent':''}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Overview({model,onGate,onConsult}:{model:MasterIndex;onGate:(g:Gate)=>void;onConsult:()=>void}){return <><section className="overview-grid"><div className="readiness panel"><div className="panel-head"><div><span className="eyebrow">INTERNAL MANAGEMENT INDICATOR</span><h2>내부 준비도</h2></div><span className="status-chip amber">Conditional GO</span></div><div className="score-row"><strong>{model.readiness.score}</strong><span>/ 100</span><div className="score-ring" style={{'--score':`${model.readiness.score*3.6}deg`} as React.CSSProperties}><div/></div></div><p>{model.readiness.note}</p><div className="progress"><i style={{width:`${model.readiness.score}%`}}/></div><div className="legend"><span><i className="dot teal"/>확보·진행 데이터</span><span><i className="dot gray"/>미착수·검증 필요</span></div></div><div className="signal panel"><div className="panel-head"><div><span className="eyebrow">PUBLICATION CONTROL</span><h2>공개 경계 상태</h2></div><ShieldCheck size={22} className="teal-text"/></div><div className="signal-line"><div className="signal-icon"><Database size={19}/></div><div><strong>PUBLIC + Y 화이트리스트</strong><p>공개 승인된 요약·메타데이터만 웹에 발행합니다.</p></div></div><div className="signal-line"><div className="signal-icon amber-bg"><Activity size={19}/></div><div><strong>Drive endpoint 미설정</strong><p>실시간 동기화 전까지 승인 스냅샷을 표시합니다.</p></div></div><button className="text-link" onClick={onConsult}>자료 열람·데이터룸 요청 <ArrowUpRight size={15}/></button></div></section><section className="section-title"><div><span className="eyebrow">READINESS GATES</span><h2>필수 Gate 진행 현황</h2></div><button className="text-link" onClick={()=>onGate(model.gates[0])}>전체 보기 <ArrowUpRight size={15}/></button></section><div className="gate-table panel"><div className="table-head"><span>GATE / 영역</span><span>진행도</span><span>상태</span><span>최근 판단</span></div>{model.gates.slice(0,6).map(g=><GateRow key={g.id} gate={g} onClick={()=>onGate(g)}/>)}</div><section className="lower-grid"><div className="panel claim-highlight"><div className="panel-head"><div><span className="eyebrow">CLAIM-EVIDENCE MATRIX</span><h2>핵심 주장과 검증상태</h2></div><FileCheck2 size={21} className="teal-text"/></div><div className="claim-row"><div className="claim-value">81 g/L</div><div><strong>동시 혼합배양 조건의 GABA 제시값</strong><p>특허출원 실시예 · <em>검증 필요</em></p></div></div><div className="notice">질량수지·독립 반복·외부 교차분석 필요</div></div><div className="panel timeline-mini"><div className="panel-head"><div><span className="eyebrow">ROADMAP</span><h2>2030 목표까지</h2></div><GitBranch size={21} className="teal-text"/></div>{model.roadmap.slice(0,3).map((r,i)=><div className="road-row" key={r.year}><span className={i===0?'now':''}>{r.year}</span><strong>{r.title}</strong></div>)}</div></section></>}
function GateRow({gate,onClick}:{gate:Gate;onClick:()=>void}){return <button className="gate-row" onClick={onClick}><div className="gate-id">{gate.id}<span>{gate.area}</span></div><div className="gate-name"><strong>{gate.title}</strong><small>{gate.publicSummary}</small></div><div className="mini-progress"><i style={{width:`${gate.checklistProgress}%`}}/><span>{gate.checklistProgress}%</span></div><div><span className={`status-chip ${gate.status}`}>{statusLabel[gate.status]}</span></div><ChevronRight size={16} className="row-arrow"/></button>}
function Gates({gates,onGate}:{gates:Gate[];onGate:(g:Gate)=>void}){const active=gates.filter(g=>g.status==='in_progress'||g.status==='complete').length;const blocked=gates.filter(g=>g.status==='blocked').length;return <><div className="filter-bar panel"><div><strong>10개 필수 Gate</strong><span>가중치 합계 {gates.reduce((s,g)=>s+g.weight,0)}% · 내부 관리지표</span></div><div className="filter-meta"><span><i className="dot teal"/> 진행·완료 {active}</span><span><i className="dot red"/> 차단 {blocked}</span></div></div><div className="gate-table panel">{gates.map(g=><GateRow key={g.id} gate={g} onClick={()=>onGate(g)}/>)}</div></>}
function SearchResults({hits,onSelect}:{hits:SearchHit[];onSelect:(hit:SearchHit)=>void}){return <div className="search-results panel" role="listbox" aria-label="통합 검색 결과">{hits.map(hit=><button key={`${hit.kind}-${hit.id}`} onClick={()=>onSelect(hit)} role="option"><span className="search-kind">{hit.kind}</span><span><strong>{hit.label}</strong><small>{hit.meta}</small></span><ArrowUpRight size={14}/></button>)}</div>}
function Technology({model}:{model:MasterIndex}){return <div className="stack"><section className="tech-intro panel"><div><span className="eyebrow">TECHNOLOGY FOUNDATION</span><h2>하이브리드 정밀발효·분리·분석·표준화</h2><p>국제기탁 복합균주를 기반으로 휴먼그레이드와 사료용을 우선 상용화하고, 코스메틱·농업은 검증 중인 확장 파이프라인으로 관리합니다.</p></div><div className="process-flow">{model.technology.process.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong>{i<2&&<ChevronRight/>}</div>)}</div></section><div className="two-col"><InfoPanel title="핵심 균주" items={model.technology.strains}/><InfoPanel title="특허출원" items={model.technology.patents}/></div><section className="panel caution"><div className="notice-icon"><Activity size={19}/></div><div><strong>표현 통제 원칙</strong><p>특허출원·기탁 사실은 공개하되, 등록특허·국제적 효능 인증·상업생산 달성으로 확대해석하지 않습니다.</p></div></section></div>}
function InfoPanel({title,items}:{title:string;items:string[]}){return <section className="panel info-panel"><div className="panel-head"><h2>{title}</h2><span className="count">{items.length}</span></div>{items.map(x=><div className="info-item" key={x}><span className="item-mark"><FileCheck2 size={15}/></span><strong>{x}</strong></div>)}</section>}
function Evidence({model}:{model:MasterIndex}){return <div className="stack"><div className="evidence-banner"><FileCheck2 size={22}/><div><strong>공개 증빙 인덱스</strong><p>원문이 아닌 공개 승인 요약·메타데이터만 노출됩니다. RESTRICTED 자료는 자료열람 요청으로 연결됩니다.</p></div></div><div className="doc-list panel">{model.documents.map(d=><div className="doc-row" key={d.id}><div className="doc-icon"><BookOpen size={18}/></div><div className="doc-title"><strong>{d.title}</strong><span>{d.category} · {d.sourceType}</span></div><span className={`status-chip ${d.publicationLevel==='PUBLIC'?'complete':'blocked'}`}>{d.publicationLevel}</span><span className="doc-date">{d.modifiedAt}</span><ArrowUpRight size={16}/></div>)}</div><div className="matrix panel"><div className="panel-head"><div><span className="eyebrow">CLAIM-EVIDENCE</span><h2>주장별 검증 한계</h2></div></div>{model.claims.map(c=><div className="matrix-row" key={c.claimId}><strong>{c.claimId}</strong><div><b>{c.publicWording}</b><p>{c.limitation}</p></div><span className={`status-chip ${c.verificationStatus==='verification_required'?'blocked':'in_progress'}`}>{c.verificationStatus==='verification_required'?'검증 필요':'부분 확인'}</span></div>)}</div></div>}
function Products({model,onConsult}:{model:MasterIndex;onConsult:(id:string)=>void}){return <div className="product-grid">{model.products.map(p=><section className="product panel" key={p.id}><div className="product-top"><span className="product-number">0{model.products.indexOf(p)+1}</span><span className={`stage ${p.stage.startsWith('우선')?'priority':''}`}>{p.stage}</span></div><h2>{p.name}</h2><p>{p.description}</p><div className="product-meta"><span>{p.market}</span><strong>{p.status}</strong></div><button className="text-link" onClick={()=>onConsult(p.id)}>제품 관련 상담 <ArrowUpRight size={15}/></button></section>)}</div>}
function Roadmap({model}:{model:MasterIndex}){return <div className="roadmap">{model.roadmap.map((r,i)=><section className="road-item" key={r.year}><div className="road-year"><span>0{i+1}</span><strong>{r.year}</strong></div><div className="road-content"><h2>{r.title}</h2>{r.items.map(x=><p key={x}><span/> {x}</p>)}</div></section>)}</div>}
function Risks({model}:{model:MasterIndex}){return <div className="risk-list">{model.risks.map(r=><section className="risk panel" key={r.id}><div className={`risk-level ${r.severity}`}>{r.severity==='high'?'HIGH':'MEDIUM'}</div><div><span className="eyebrow">{r.id}</span><h2>{r.title}</h2><p>대응: {r.mitigation}</p></div><ArrowUpRight size={17}/></section>)}</div>}
function ConsultationPage({onOpen}:{onOpen:(categoryId:string)=>void}){return <div className="stack"><section className="evidence-banner"><Handshake size={22}/><div><strong>조건형 협업·상담</strong><p>상담 목적을 선택하면 현재 보고 있던 Gate·제품·자료 문맥을 문의 요약에 연결합니다.</p></div></section><div className="category-grid">{categoryOptions.map(c=><button className="category-card panel" key={c.id} onClick={()=>onOpen(c.id)}><span>{c.id.toUpperCase()}</span><h2>{c.name}</h2><p>{c.description}</p><ArrowUpRight size={16}/></button>)}</div></div>}
function Generic({section,model}:{section:Section;model:MasterIndex}){const copy:Record<string,[string,string]>= {experiments:['실험·검증','특허출원 실시예와 독립 반복·외부 교차분석을 분리해 기록하는 영역입니다.'],scaleup:['Scale-up·제조','300 L 파일럿 재현성과 QA·QC 체계를 Gate 기준으로 관리합니다.'],esg:['ESG·바이오셀룰로오스','바이오셀룰로오스·LCA·MRV 및 농업·건축소재 확장 가능성을 검증 단계로 관리합니다.'],finance:['재무·지배구조','K-IFRS·내부통제·지정감사 준비의 선행조건과 증빙을 관리합니다.']}; const [title,desc]=copy[section]!; const rows=section==='experiments'?model.experiments:section==='scaleup'?model.experiments.filter((x:any)=>String(x.gateId||'').includes('G04')):[]; return <div className="stack"><div className="empty-state panel"><div className="empty-icon"><Database size={25}/></div><h2>{title} 운영영역</h2><p>{desc}</p><div className="empty-note">현재 공개 데이터 기준 연결된 항목: {section==='esg'?model.esg.length:rows.length}건 · 원본은 Google Drive에서 관리</div></div>{section==='esg'&&<div className="info-panel panel">{model.esg.map(item=><div className="info-item" key={item}><span className="item-mark"><Leaf size={15}/></span><strong>{item}</strong></div>)}</div>}{rows.length>0&&<div className="data-list panel">{rows.map((row:any)=><div className="data-row" key={String(row.id)}><strong>{row.id}</strong><span>{row.title}</span><em>{row.status}</em></div>)}</div>}</div>}
function GateDrawer({gate,onClose,onConsult}:{gate:Gate;onClose:()=>void;onConsult:()=>void}){return <><div className="drawer-scrim" onClick={onClose}/><aside className="drawer"><div className="drawer-head"><span className="eyebrow">{gate.id} · {gate.area}</span><button onClick={onClose} aria-label="상세 닫기"><X size={19}/></button></div><h2>{gate.title}</h2><p>{gate.description}</p><div className="drawer-status"><span className={`status-chip ${gate.status}`}>{statusLabel[gate.status]}</span><strong>{gate.checklistProgress}% 진행</strong></div><div className="drawer-section"><small>통과 기준</small><p>{gate.passCriteria}</p></div><div className="drawer-section"><small>공개 요약</small><p>{gate.publicSummary}</p></div><div className="drawer-section"><small>연결 증빙</small><p>{gate.evidenceCount}건 · 공개 승인 요약 기준</p></div><button className="primary full" onClick={onConsult}>이 Gate 관련 상담 요청 <ArrowUpRight size={16}/></button></aside></>}
function Consultation({onClose,context}:{onClose:()=>void;context?:string}){const [step,setStep]=useState(1); const [category,setCategory]=useState('scaleup'); const [sent,setSent]=useState(false); const [name,setName]=useState(''); const [company,setCompany]=useState(''); const [email,setEmail]=useState(''); return <><div className="modal-scrim" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">COLLABORATION INQUIRY</span><h2>{sent?'접수 완료':'조건형 협업 문의'}</h2></div><button onClick={onClose} aria-label="문의 닫기"><X size={19}/></button></div>{sent?<div className="success"><div>✓</div><h3>문의가 접수되었습니다</h3><p>접수번호 <strong>REQ-20260810-001</strong><br/>담당자가 영업일 기준 2일 이내 회신합니다.</p><button className="primary" onClick={onClose}>닫기</button></div>:<><div className="steps"><span className="active">01 목적</span><span className={step>1?'active':''}>02 기본정보</span><span>03 미리보기</span></div>{step===1?<div className="form"><label>상담 목적<select value={category} onChange={e=>setCategory(e.target.value)}><option value="scaleup">발효 Scale-up·OEM</option><option value="ipo">기술성평가·IPO</option><option value="patent">특허·라이선스</option><option value="product">제품·샘플</option></select></label><div className="context"><Target size={16}/><span>현재 문맥: {context??'종합현황'} · 공개 데이터 버전 {model.schemaVersion}</span></div><label>추가 메시지<textarea placeholder="상담 목적과 필요한 자료를 간단히 적어주세요."/></label><button className="primary full" onClick={()=>setStep(2)}>다음 단계 <ChevronRight size={16}/></button></div>:<div className="form"><label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="홍길동"/></label><label>회사·기관명<input value={company} onChange={e=>setCompany(e.target.value)} placeholder="회사명"/></label><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label className="check"><input type="checkbox"/> 개인정보 수집·이용에 동의합니다.</label><div className="preview">{company||'회사·기관명'}의 담당자가 {category==='scaleup'?'발효 Scale-up·OEM':'선택한 상담 목적'}에 관해 상담을 요청합니다.{context&&` 현재 확인 중인 ${context} Gate 문맥이 연결되었습니다.`}</div><button className="primary full" disabled={!name||!company||!email} onClick={()=>setSent(true)}>문의 제출 <ArrowUpRight size={16}/></button><button className="back" onClick={()=>setStep(1)}>이전</button></div>}</>}</div></>}
createRoot(document.getElementById('root')!).render(<App/>);

function ConsultationV2({onClose,context,initialCategory='scaleup'}:{onClose:()=>void;context?:string;initialCategory?:string}){
 const [step,setStep]=useState(1); const [category,setCategory]=useState(initialCategory); const [name,setName]=useState(''); const [company,setCompany]=useState(''); const [role,setRole]=useState(''); const [email,setEmail]=useState(''); const [message,setMessage]=useState(''); const [consent,setConsent]=useState(false); const [sending,setSending]=useState(false); const [error,setError]=useState(''); const [requestId,setRequestId]=useState('');
 const endpoint=import.meta.env.VITE_CONSULTATION_ENDPOINT as string|undefined;
 const categoryName=categoryOptions.find(item=>item.id===category)?.name||category;
 const submit=async()=>{setError(''); if(!endpoint){setError('문의 접수 endpoint가 아직 연결되지 않았습니다. 운영자에게 endpoint 설정을 요청해 주세요.');return} setSending(true); try{const body=new URLSearchParams({name,company,role,email,categoryId:category,categoryName,gateId:context||'',currentUrl:window.location.href,requestType:categoryName,message,consent:String(consent),formStartedAt:String(Date.now()-10000)}); const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body}); const payload=await response.json(); if(!response.ok||!payload.ok)throw new Error(payload.error||'문의 접수에 실패했습니다.'); setRequestId(payload.requestId||'접수 완료'); setStep(4)}catch(e){setError(e instanceof Error?e.message:'문의 접수에 실패했습니다.')}finally{setSending(false)}};
 return <><div className="modal-scrim" onClick={onClose}/><div className="modal" role="dialog" aria-modal="true" aria-labelledby="consult-title"><div className="modal-head"><div><span className="eyebrow">COLLABORATION INQUIRY</span><h2 id="consult-title">{step===4?'접수 완료':'조건형 협업 문의'}</h2></div><button onClick={onClose} aria-label="문의 닫기"><X size={19}/></button></div>{step===4?<div className="success"><div>✓</div><h3>문의가 접수되었습니다</h3><p>접수번호 <strong>{requestId}</strong><br/>담당자가 영업일 기준 2일 이내 회신합니다.</p><button className="primary" onClick={onClose}>닫기</button></div>:<><div className="steps"><span className={step>=1?'active':''}>01 목적</span><span className={step>=2?'active':''}>02 기본정보</span><span className={step>=3?'active':''}>03 미리보기</span></div>{step===1?<div className="form"><label>상담 목적<select value={category} onChange={e=>setCategory(e.target.value)}>{categoryOptions.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="context"><Target size={16}/><span>현재 문맥: {context??'종합현황'} · 공개 데이터 버전 {model.schemaVersion}</span></div><label>{categoryQuestions[category]||'협업 목적과 필요한 지원 범위를 알려주세요.'}<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={3000} placeholder="조건·일정·필요 자료를 간단히 적어주세요."/></label><button className="primary full" onClick={()=>setStep(2)}>다음 단계 <ChevronRight size={16}/></button></div>:step===2?<div className="form"><label>이름<input value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder="홍길동"/></label><label>회사·기관명<input value={company} onChange={e=>setCompany(e.target.value)} maxLength={200} placeholder="회사명"/></label><label>직책·역할<input value={role} onChange={e=>setRole(e.target.value)} maxLength={200} placeholder="담당자"/></label><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={300} placeholder="name@company.com"/></label><label className="check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> 개인정보 수집·이용에 동의합니다.</label><button className="primary full" disabled={!name||!company||!email||!consent} onClick={()=>setStep(3)}>미리보기 <ChevronRight size={16}/></button><button className="back" onClick={()=>setStep(1)}>이전</button></div>:<div className="form"><div className="preview"><strong>{categoryName}</strong><br/>{company}의 {role||'담당자'}가 {categoryName} 상담을 요청합니다.<br/>{message||'추가 메시지 없음'}<br/><small>문맥: {context||'종합현황'} · 회신: {email}</small></div>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary full" disabled={sending} onClick={submit}>{sending?'전송 중…':'문의 제출'} <ArrowUpRight size={16}/></button><button className="back" onClick={()=>setStep(2)}>이전</button></div>}</>}</div></>;
}
