import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowUpRight, Beaker, BookOpen, Boxes, Building2, ChevronRight, ClipboardCheck, Database, FileCheck2, FlaskConical, GitBranch, Leaf, Menu, Search, ShieldCheck, Target, X} from 'lucide-react';
import data from './data/master-index.json';
import type {MasterIndex, Section, Gate} from './types';
import './styles.css';

const model = data as MasterIndex;
const nav: {id:Section; label:string; icon:React.ElementType}[] = [
  {id:'overview',label:'종합현황',icon:Activity},{id:'technology',label:'핵심기술',icon:Beaker},{id:'gates',label:'필수 Gate',icon:Target},{id:'evidence',label:'증빙자료',icon:FileCheck2},{id:'experiments',label:'실험·검증',icon:FlaskConical},{id:'scaleup',label:'Scale-up·제조',icon:Boxes},{id:'products',label:'제품·시장',icon:Building2},{id:'esg',label:'ESG·바이오셀룰로오스',icon:Leaf},{id:'finance',label:'재무·지배구조',icon:ShieldCheck},{id:'roadmap',label:'로드맵',icon:GitBranch},{id:'risks',label:'리스크',icon:ClipboardCheck}
];
const statusLabel:Record<string,string>={complete:'완료',in_progress:'진행 중',not_started:'미착수',blocked:'차단'};
function App(){
 const [section,setSection]=useState<Section>('overview'); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(''); const [selectedGate,setSelectedGate]=useState<Gate|null>(null); const [consult,setConsult]=useState(false);
 const filteredGates=useMemo(()=>model.gates.filter(g=>`${g.id} ${g.title} ${g.area}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const go=(id:Section)=>{setSection(id);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="app-shell">
  <aside className={`sidebar ${mobile?'open':''}`}><div className="brand"><div className="brand-mark">N</div><div><strong>MASTER INDEX</strong><span>기술특례상장 준비</span></div><button className="close-nav" onClick={()=>setMobile(false)} aria-label="메뉴 닫기"><X size={18}/></button></div><div className="nav-group"><small>OPERATING SYSTEM</small>{nav.map(({id,label,icon:Icon})=><button key={id} className={section===id?'active':''} onClick={()=>go(id)}><Icon size={17}/><span>{label}</span>{id==='gates'&&<b>10</b>}</button>)}</div><div className="sidebar-bottom"><div className="sync-dot"/><div><small>데이터 상태</small><strong>승인 스냅샷</strong></div></div></aside>
  {mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<main className="main"><header className="topbar"><button className="menu-btn" onClick={()=>setMobile(true)} aria-label="메뉴 열기"><Menu size={20}/></button><div className="crumb">2030 상장 준비 <ChevronRight size={14}/> {nav.find(n=>n.id===section)?.label ?? '종합현황'}</div><div className="top-actions"><div className="search"><Search size={16}/><input aria-label="Gate 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Gate, 자료 검색"/></div><span className="env"><i/>PUBLIC VIEW</span></div></header>
   <div className="content"><div className="page-head"><div><p className="kicker">CONDITIONAL GO · 2030 LISTING ROADMAP</p><h1>{section==='overview'?'기술특례상장 준비 현황':nav.find(n=>n.id===section)?.label}</h1><p className="subhead">Precision-Fermented GABA Biomaterials Platform <span>·</span> 공개 승인 데이터 기준</p></div><button className="primary" onClick={()=>setConsult(true)}>협업 문의 시작 <ArrowUpRight size={16}/></button></div>
    {section==='overview'&&<Overview model={model} onGate={(g)=>{setSelectedGate(g);setSection('gates')}} onConsult={()=>setConsult(true)}/>} {section==='gates'&&<Gates gates={filteredGates} onGate={setSelectedGate}/>} {section==='technology'&&<Technology model={model}/>} {section==='evidence'&&<Evidence model={model}/>} {section==='products'&&<Products model={model}/>} {section==='roadmap'&&<Roadmap model={model}/>} {section==='risks'&&<Risks model={model}/>} {['experiments','scaleup','esg','finance'].includes(section)&&<Generic section={section} model={model}/>}<footer><span>Master Web Index · v{model.schemaVersion}</span><span>마지막 승인 동기화 {model.source.lastSyncedAt.slice(0,10)} · {model.syncHealth.status}</span></footer></div>
  </main>{selectedGate&&<GateDrawer gate={selectedGate} onClose={()=>setSelectedGate(null)} onConsult={()=>{setSelectedGate(null);setConsult(true)}}/>}{consult&&<Consultation onClose={()=>setConsult(false)} context={selectedGate?.id}/>}</div>
}
function Metric({label,value,note,accent=false}:{label:string;value:string;note:string;accent?:boolean}){return <div className={`metric ${accent?'accent':''}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Overview({model,onGate,onConsult}:{model:MasterIndex;onGate:(g:Gate)=>void;onConsult:()=>void}){return <><section className="overview-grid"><div className="readiness panel"><div className="panel-head"><div><span className="eyebrow">INTERNAL MANAGEMENT INDICATOR</span><h2>내부 준비도</h2></div><span className="status-chip amber">Conditional GO</span></div><div className="score-row"><strong>{model.readiness.score}</strong><span>/ 100</span><div className="score-ring" style={{'--score':`${model.readiness.score*3.6}deg`} as React.CSSProperties}><div/></div></div><p>{model.readiness.note}</p><div className="progress"><i style={{width:`${model.readiness.score}%`}}/></div><div className="legend"><span><i className="dot teal"/>확보·진행 데이터</span><span><i className="dot gray"/>미착수·검증 필요</span></div></div><div className="signal panel"><div className="panel-head"><div><span className="eyebrow">PUBLICATION CONTROL</span><h2>공개 경계 상태</h2></div><ShieldCheck size={22} className="teal-text"/></div><div className="signal-line"><div className="signal-icon"><Database size={19}/></div><div><strong>PUBLIC + Y 화이트리스트</strong><p>공개 승인된 요약·메타데이터만 웹에 발행합니다.</p></div></div><div className="signal-line"><div className="signal-icon amber-bg"><Activity size={19}/></div><div><strong>Drive endpoint 미설정</strong><p>실시간 동기화 전까지 승인 스냅샷을 표시합니다.</p></div></div><button className="text-link" onClick={onConsult}>자료 열람·데이터룸 요청 <ArrowUpRight size={15}/></button></div></section><section className="section-title"><div><span className="eyebrow">READINESS GATES</span><h2>필수 Gate 진행 현황</h2></div><button className="text-link" onClick={()=>onGate(model.gates[0])}>전체 보기 <ArrowUpRight size={15}/></button></section><div className="gate-table panel"><div className="table-head"><span>GATE / 영역</span><span>진행도</span><span>상태</span><span>최근 판단</span></div>{model.gates.slice(0,6).map(g=><GateRow key={g.id} gate={g} onClick={()=>onGate(g)}/>)}</div><section className="lower-grid"><div className="panel claim-highlight"><div className="panel-head"><div><span className="eyebrow">CLAIM-EVIDENCE MATRIX</span><h2>핵심 주장과 검증상태</h2></div><FileCheck2 size={21} className="teal-text"/></div><div className="claim-row"><div className="claim-value">81 g/L</div><div><strong>동시 혼합배양 조건의 GABA 제시값</strong><p>특허출원 실시예 · <em>검증 필요</em></p></div></div><div className="notice">질량수지·독립 반복·외부 교차분석 필요</div></div><div className="panel timeline-mini"><div className="panel-head"><div><span className="eyebrow">ROADMAP</span><h2>2030 목표까지</h2></div><GitBranch size={21} className="teal-text"/></div>{model.roadmap.slice(0,3).map((r,i)=><div className="road-row" key={r.year}><span className={i===0?'now':''}>{r.year}</span><strong>{r.title}</strong></div>)}</div></section></>}
function GateRow({gate,onClick}:{gate:Gate;onClick:()=>void}){return <button className="gate-row" onClick={onClick}><div className="gate-id">{gate.id}<span>{gate.area}</span></div><div className="gate-name"><strong>{gate.title}</strong><small>{gate.publicSummary}</small></div><div className="mini-progress"><i style={{width:`${gate.checklistProgress}%`}}/><span>{gate.checklistProgress}%</span></div><div><span className={`status-chip ${gate.status}`}>{statusLabel[gate.status]}</span></div><ChevronRight size={16} className="row-arrow"/></button>}
function Gates({gates,onGate}:{gates:Gate[];onGate:(g:Gate)=>void}){return <><div className="filter-bar panel"><div><strong>10개 필수 Gate</strong><span>가중치 합계 100% · 내부 관리지표</span></div><div className="filter-meta"><span><i className="dot teal"/> 진행·완료 4</span><span><i className="dot red"/> 차단 1</span></div></div><div className="gate-table panel">{gates.map(g=><GateRow key={g.id} gate={g} onClick={()=>onGate(g)}/>)}</div></>}
function Technology({model}:{model:MasterIndex}){return <div className="stack"><section className="tech-intro panel"><div><span className="eyebrow">TECHNOLOGY FOUNDATION</span><h2>하이브리드 정밀발효·분리·분석·표준화</h2><p>국제기탁 복합균주를 기반으로 휴먼그레이드와 사료용을 우선 상용화하고, 코스메틱·농업은 검증 중인 확장 파이프라인으로 관리합니다.</p></div><div className="process-flow">{model.technology.process.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong>{i<2&&<ChevronRight/>}</div>)}</div></section><div className="two-col"><InfoPanel title="핵심 균주" items={model.technology.strains}/><InfoPanel title="특허출원" items={model.technology.patents}/></div><section className="panel caution"><div className="notice-icon"><Activity size={19}/></div><div><strong>표현 통제 원칙</strong><p>특허출원·기탁 사실은 공개하되, 등록특허·국제적 효능 인증·상업생산 달성으로 확대해석하지 않습니다.</p></div></section></div>}
function InfoPanel({title,items}:{title:string;items:string[]}){return <section className="panel info-panel"><div className="panel-head"><h2>{title}</h2><span className="count">{items.length}</span></div>{items.map(x=><div className="info-item" key={x}><span className="item-mark"><FileCheck2 size={15}/></span><strong>{x}</strong></div>)}</section>}
function Evidence({model}:{model:MasterIndex}){return <div className="stack"><div className="evidence-banner"><FileCheck2 size={22}/><div><strong>공개 증빙 인덱스</strong><p>원문이 아닌 공개 승인 요약·메타데이터만 노출됩니다. RESTRICTED 자료는 자료열람 요청으로 연결됩니다.</p></div></div><div className="doc-list panel">{model.documents.map(d=><div className="doc-row" key={d.id}><div className="doc-icon"><BookOpen size={18}/></div><div className="doc-title"><strong>{d.title}</strong><span>{d.category} · {d.sourceType}</span></div><span className={`status-chip ${d.publicationLevel==='PUBLIC'?'complete':'blocked'}`}>{d.publicationLevel}</span><span className="doc-date">{d.modifiedAt}</span><ArrowUpRight size={16}/></div>)}</div><div className="matrix panel"><div className="panel-head"><div><span className="eyebrow">CLAIM-EVIDENCE</span><h2>주장별 검증 한계</h2></div></div>{model.claims.map(c=><div className="matrix-row" key={c.claimId}><strong>{c.claimId}</strong><div><b>{c.publicWording}</b><p>{c.limitation}</p></div><span className={`status-chip ${c.verificationStatus==='verification_required'?'blocked':'in_progress'}`}>{c.verificationStatus==='verification_required'?'검증 필요':'부분 확인'}</span></div>)}</div></div>}
function Products({model}:{model:MasterIndex}){return <div className="product-grid">{model.products.map(p=><section className="product panel" key={p.id}><div className="product-top"><span className="product-number">0{model.products.indexOf(p)+1}</span><span className={`stage ${p.stage.startsWith('우선')?'priority':''}`}>{p.stage}</span></div><h2>{p.name}</h2><p>{p.description}</p><div className="product-meta"><span>{p.market}</span><strong>{p.status}</strong></div><button className="text-link">제품 관련 상담 <ArrowUpRight size={15}/></button></section>)}</div>}
function Roadmap({model}:{model:MasterIndex}){return <div className="roadmap">{model.roadmap.map((r,i)=><section className="road-item" key={r.year}><div className="road-year"><span>0{i+1}</span><strong>{r.year}</strong></div><div className="road-content"><h2>{r.title}</h2>{r.items.map(x=><p key={x}><span/> {x}</p>)}</div></section>)}</div>}
function Risks({model}:{model:MasterIndex}){return <div className="risk-list">{model.risks.map(r=><section className="risk panel" key={r.id}><div className={`risk-level ${r.severity}`}>{r.severity==='high'?'HIGH':'MEDIUM'}</div><div><span className="eyebrow">{r.id}</span><h2>{r.title}</h2><p>대응: {r.mitigation}</p></div><ArrowUpRight size={17}/></section>)}</div>}
function Generic({section,model}:{section:Section;model:MasterIndex}){const copy:Record<string,[string,string]>= {experiments:['실험·검증','특허출원 실시예와 독립 반복·외부 교차분석을 분리해 기록하는 영역입니다.'],scaleup:['Scale-up·제조','300 L 파일럿 재현성과 QA·QC 체계를 Gate 기준으로 관리합니다.'],esg:['ESG·바이오셀룰로오스','바이오셀룰로오스·LCA·MRV 및 농업·건축소재 확장 가능성을 검증 단계로 관리합니다.'],finance:['재무·지배구조','K-IFRS·내부통제·지정감사 준비의 선행조건과 증빙을 관리합니다.']}; const [title,desc]=copy[section]!; return <div className="empty-state panel"><div className="empty-icon"><Database size={25}/></div><h2>{title} 운영영역</h2><p>{desc}</p><div className="empty-note">현재 공개 데이터 기준 연결된 항목: {section==='esg'?model.esg.length:0}건 · 원본은 Google Drive에서 관리</div></div>}
function GateDrawer({gate,onClose,onConsult}:{gate:Gate;onClose:()=>void;onConsult:()=>void}){return <><div className="drawer-scrim" onClick={onClose}/><aside className="drawer"><div className="drawer-head"><span className="eyebrow">{gate.id} · {gate.area}</span><button onClick={onClose} aria-label="상세 닫기"><X size={19}/></button></div><h2>{gate.title}</h2><p>{gate.description}</p><div className="drawer-status"><span className={`status-chip ${gate.status}`}>{statusLabel[gate.status]}</span><strong>{gate.checklistProgress}% 진행</strong></div><div className="drawer-section"><small>통과 기준</small><p>{gate.passCriteria}</p></div><div className="drawer-section"><small>공개 요약</small><p>{gate.publicSummary}</p></div><div className="drawer-section"><small>연결 증빙</small><p>{gate.evidenceCount}건 · 공개 승인 요약 기준</p></div><button className="primary full" onClick={onConsult}>이 Gate 관련 상담 요청 <ArrowUpRight size={16}/></button></aside></>}
function Consultation({onClose,context}:{onClose:()=>void;context?:string}){const [step,setStep]=useState(1); const [category,setCategory]=useState('scaleup'); const [sent,setSent]=useState(false); const [name,setName]=useState(''); const [company,setCompany]=useState(''); const [email,setEmail]=useState(''); return <><div className="modal-scrim" onClick={onClose}/><div className="modal"><div className="modal-head"><div><span className="eyebrow">COLLABORATION INQUIRY</span><h2>{sent?'접수 완료':'조건형 협업 문의'}</h2></div><button onClick={onClose} aria-label="문의 닫기"><X size={19}/></button></div>{sent?<div className="success"><div>✓</div><h3>문의가 접수되었습니다</h3><p>접수번호 <strong>REQ-20260810-001</strong><br/>담당자가 영업일 기준 2일 이내 회신합니다.</p><button className="primary" onClick={onClose}>닫기</button></div>:<><div className="steps"><span className="active">01 목적</span><span className={step>1?'active':''}>02 기본정보</span><span>03 미리보기</span></div>{step===1?<div className="form"><label>상담 목적<select value={category} onChange={e=>setCategory(e.target.value)}><option value="scaleup">발효 Scale-up·OEM</option><option value="ipo">기술성평가·IPO</option><option value="patent">특허·라이선스</option><option value="product">제품·샘플</option></select></label><div className="context"><Target size={16}/><span>현재 문맥: {context??'종합현황'} · 공개 데이터 버전 {model.schemaVersion}</span></div><label>추가 메시지<textarea placeholder="상담 목적과 필요한 자료를 간단히 적어주세요."/></label><button className="primary full" onClick={()=>setStep(2)}>다음 단계 <ChevronRight size={16}/></button></div>:<div className="form"><label>이름<input value={name} onChange={e=>setName(e.target.value)} placeholder="홍길동"/></label><label>회사·기관명<input value={company} onChange={e=>setCompany(e.target.value)} placeholder="회사명"/></label><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label className="check"><input type="checkbox"/> 개인정보 수집·이용에 동의합니다.</label><div className="preview">{company||'회사·기관명'}의 담당자가 {category==='scaleup'?'발효 Scale-up·OEM':'선택한 상담 목적'}에 관해 상담을 요청합니다.{context&&` 현재 확인 중인 ${context} Gate 문맥이 연결되었습니다.`}</div><button className="primary full" disabled={!name||!company||!email} onClick={()=>setSent(true)}>문의 제출 <ArrowUpRight size={16}/></button><button className="back" onClick={()=>setStep(1)}>이전</button></div>}</>}</div></>}
createRoot(document.getElementById('root')!).render(<App/>);
